export const FETCH_RECIPES_START = 'FETCH_RECIPES_START';
export const FETCH_RECIPES_SUCCESS = 'FETCH_RECIPES_SUCCESS';

export const FETCH_RECIPE_INFO_START = 'FETCH_RECIPE_INFO_START';
export const FETCH_RECIPE_INFO_SUCCESS = 'FETCH_RECIPE_INFO_SUCCESS';

export const DELETE_RECIPE = 'DELETE_RECIPE';